"use client";

import { motion } from "framer-motion";

const experience = [["now", "Open source", "Building and sharing public projects"], ["recent", "AI tools", "Exploring assistants and intelligent workflows"], ["ongoing", "Web projects", "Creating practical digital experiences"]];
const capabilities = ["JavaScript", "AI projects", "Web applications", "Real-time data", "Product thinking", "Rapid prototyping"];

export default function About() {
  return <section id="about" className="border-t border-white/10 px-5 py-24 sm:px-8 lg:px-12"><div className="mx-auto max-w-7xl"><div className="grid gap-16 lg:grid-cols-[.8fr_1.2fr]"><div><p className="mb-4 text-xs uppercase tracking-[.22em] text-[#ff3b30]">About Rasswanth</p><h2 className="font-display text-4xl tracking-[-.06em] text-white sm:text-6xl">Curious by<br /><span className="text-zinc-600">nature.</span><br />Useful by choice.</h2></div><div className="max-w-2xl"><p className="text-xl leading-8 tracking-[-.02em] text-zinc-300 sm:text-2xl">I build practical software at the intersection of AI, web applications, and real-time data. I like turning rough ideas into tools people can actually use.</p><p className="mt-7 text-sm leading-7 text-zinc-500">My public work is an evolving record of experiments, problem-solving, and learning in the open.</p></div></div><div className="mt-24 grid gap-16 border-t border-white/10 pt-8 md:grid-cols-[.8fr_1.2fr]"><h3 className="text-xs uppercase tracking-[.22em] text-zinc-500">What I&apos;m working on</h3><div>{experience.map(item => <motion.div whileHover={{ x: 5 }} key={item[0]} className="grid grid-cols-[90px_1fr] gap-4 border-b border-white/10 py-5 text-sm sm:grid-cols-[120px_1fr_1fr]"><span className="font-mono text-xs uppercase text-zinc-600">{item[0]}</span><span className="text-white">{item[1]}</span><span className="text-zinc-500 sm:text-right">{item[2]}</span></motion.div>)}</div></div><div className="mt-16 grid gap-8 border-t border-white/10 pt-8 md:grid-cols-[.8fr_1.2fr]"><h3 className="text-xs uppercase tracking-[.22em] text-zinc-500">Core capabilities</h3><div className="flex max-w-2xl flex-wrap gap-2">{capabilities.map(cap => <span key={cap} className="rounded-full border border-white/15 px-4 py-2 text-sm text-zinc-300 transition-colors hover:border-[#ff3b30] hover:text-[#ff3b30]">{cap}</span>)}</div></div></div></section>;
}
