"use client";

import { ArrowLeft, ArrowRight, ArrowUpRight, ExternalLink } from "lucide-react";
import { motion } from "framer-motion";
import { useRef } from "react";

const projects = [
  { number: "01", title: "Project AI", type: "AI, personal assistant", description: "A personal AI assistant project exploring useful automation and conversational tools.", tags: ["AI", "JavaScript"], url: "https://github.com/rasswanth33-lab/project-ai", color: "#b8d5c2", text: "#14221b" },
  { number: "02", title: "Interview Simulator", type: "Web app, JavaScript", description: "A practical interview preparation tool designed to make repeated practice feel more focused.", tags: ["JavaScript", "Product"], url: "https://github.com/rasswanth33-lab/INTREVIEW-SIMULATOR", color: "#d8c8fc", text: "#282030" },
  { number: "03", title: "AI Trading", type: "Markets, real-time data", description: "An experiment with real-time crypto and stock market data for faster financial insights.", tags: ["Trading", "JavaScript"], url: "https://github.com/rasswanth33-lab/AI-Trading-", color: "#f1d487", text: "#302716" },
  { number: "04", title: "Vadhanya", type: "Web, brand site", description: "A web experience for Vadhanya Milk Products, built to give a local brand a clear digital home.", tags: ["Web design", "JavaScript"], url: "https://github.com/rasswanth33-lab/vadhanya-milk-products-web", color: "#c6d9f0", text: "#182333" },
];

export default function Projects() {
  const railRef = useRef(null);
  const slide = (direction) => railRef.current?.scrollBy({ left: direction * railRef.current.clientWidth * 0.82, behavior: "smooth" });

  return <section id="projects" className="border-t border-white/10 px-5 py-24 sm:px-8 lg:px-12"><div className="mx-auto max-w-7xl"><div className="mb-14 flex items-end justify-between"><div><p className="mb-4 text-xs uppercase tracking-[.22em] text-[#ff3b30]">Selected work / GitHub</p><h2 className="font-display text-4xl tracking-[-.06em] text-white sm:text-6xl">A few things<br /><span className="text-zinc-600">I&apos;ve built.</span></h2></div><div className="flex items-center gap-2"><button type="button" aria-label="Previous project" onClick={() => slide(-1)} className="flex h-10 w-10 items-center justify-center rounded-full border border-white/15 text-zinc-400 transition-colors hover:border-[#ff3b30] hover:text-[#ff3b30]"><ArrowLeft size={16} /></button><button type="button" aria-label="Next project" onClick={() => slide(1)} className="flex h-10 w-10 items-center justify-center rounded-full border border-white/15 text-zinc-400 transition-colors hover:border-[#ff3b30] hover:text-[#ff3b30]"><ArrowRight size={16} /></button></div></div><div ref={railRef} className="flex snap-x snap-mandatory gap-5 overflow-x-auto overscroll-x-contain pb-5 scrollbar-none"><div className="w-[1px] shrink-0" />{projects.map(project => <motion.a href={project.url} target="_blank" rel="noreferrer" drag="x" dragConstraints={{ left: 0, right: 0 }} whileHover={{ y: -5 }} transition={{ duration: .25 }} key={project.title} className="group block w-[min(84vw,560px)] shrink-0 snap-start"><div style={{ backgroundColor: project.color, color: project.text }} className="relative flex aspect-[1.25] flex-col justify-between overflow-hidden rounded-[2px] p-6 sm:p-8"><div className="flex items-start justify-between"><span className="font-mono text-xs opacity-60">{project.number} / 04</span><ArrowUpRight size={22} /></div><div><div className="mb-5 flex flex-wrap gap-2">{project.tags.map(tag => <span key={tag} className="rounded-full border border-current/20 px-3 py-1 text-[10px] uppercase tracking-[.14em] opacity-70">{tag}</span>)}</div><h3 className="font-display text-4xl font-medium tracking-[-.07em] sm:text-5xl">{project.title}</h3><p className="mt-2 max-w-sm text-sm leading-6 opacity-70">{project.description}</p></div></div><div className="flex items-center justify-between border-x border-b border-white/10 px-4 py-3 text-xs text-zinc-500"><span>{project.type}</span><span className="flex items-center gap-1 opacity-0 transition-opacity group-hover:opacity-100">Open on GitHub <ExternalLink size={12} /></span></div></motion.a>)}</div></div></section>;
}
